version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: s2o-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: s2o_pro_db
    ports:
      - "5433:5432"
    volumes:
      - s2o-pg-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: s2o-redis
    ports:
      - "6379:6379"
    volumes:
      - s2o-redis-data:/data
    restart: unless-stopped

volumes:
  s2o-pg-data:
  s2o-redis-data: